title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: false
theme: jekyll-theme-cayman
github:
  repository_url: https://github.com/epfl-ada/ada-2021-project-improvise-adapt-overcome
  owner_url: https://github.com/epfl-ada
  